// The 66 books of the Protestant canon in order, with OSIS ids, display
// names, common abbreviations (for reference parsing), and the file name used
// by the World English Bible data package.
export const BOOKS = [
  ['Gen', 'Genesis', ['gen', 'ge', 'gn'], 'genesis'],
  ['Exod', 'Exodus', ['exod', 'exo', 'ex'], 'exodus'],
  ['Lev', 'Leviticus', ['lev', 'le', 'lv'], 'leviticus'],
  ['Num', 'Numbers', ['num', 'nu', 'nm', 'nb'], 'numbers'],
  ['Deut', 'Deuteronomy', ['deut', 'deu', 'dt', 'de'], 'deuteronomy'],
  ['Josh', 'Joshua', ['josh', 'jos', 'jsh'], 'joshua'],
  ['Judg', 'Judges', ['judg', 'jdg', 'jg', 'jdgs'], 'judges'],
  ['Ruth', 'Ruth', ['ruth', 'rth', 'ru'], 'ruth'],
  ['1Sam', '1 Samuel', ['1sam', '1sa', '1sm', '1s', 'isamuel', 'firstsamuel'], '1samuel'],
  ['2Sam', '2 Samuel', ['2sam', '2sa', '2sm', '2s', 'iisamuel', 'secondsamuel'], '2samuel'],
  ['1Kgs', '1 Kings', ['1kgs', '1ki', '1kin', '1k', 'ikings', 'firstkings'], '1kings'],
  ['2Kgs', '2 Kings', ['2kgs', '2ki', '2kin', '2k', 'iikings', 'secondkings'], '2kings'],
  ['1Chr', '1 Chronicles', ['1chr', '1ch', '1chron', 'ichronicles', 'firstchronicles'], '1chronicles'],
  ['2Chr', '2 Chronicles', ['2chr', '2ch', '2chron', 'iichronicles', 'secondchronicles'], '2chronicles'],
  ['Ezra', 'Ezra', ['ezra', 'ezr', 'ez'], 'ezra'],
  ['Neh', 'Nehemiah', ['neh', 'ne'], 'nehemiah'],
  ['Esth', 'Esther', ['esth', 'est', 'es'], 'esther'],
  ['Job', 'Job', ['job', 'jb'], 'job'],
  ['Ps', 'Psalms', ['ps', 'psa', 'psalm', 'pslm', 'psm', 'pss'], 'psalms'],
  ['Prov', 'Proverbs', ['prov', 'pro', 'prv', 'pr'], 'proverbs'],
  ['Eccl', 'Ecclesiastes', ['eccl', 'ecc', 'eccles', 'ec', 'qoh'], 'ecclesiastes'],
  ['Song', 'Song of Solomon', ['song', 'sos', 'so', 'songofsongs', 'canticles', 'cant'], 'songofsolomon'],
  ['Isa', 'Isaiah', ['isa', 'is'], 'isaiah'],
  ['Jer', 'Jeremiah', ['jer', 'je', 'jr'], 'jeremiah'],
  ['Lam', 'Lamentations', ['lam', 'la'], 'lamentations'],
  ['Ezek', 'Ezekiel', ['ezek', 'eze', 'ezk'], 'ezekiel'],
  ['Dan', 'Daniel', ['dan', 'da', 'dn'], 'daniel'],
  ['Hos', 'Hosea', ['hos', 'ho'], 'hosea'],
  ['Joel', 'Joel', ['joel', 'jl'], 'joel'],
  ['Amos', 'Amos', ['amos', 'am'], 'amos'],
  ['Obad', 'Obadiah', ['obad', 'ob'], 'obadiah'],
  ['Jonah', 'Jonah', ['jonah', 'jnh', 'jon'], 'jonah'],
  ['Mic', 'Micah', ['mic', 'mc'], 'micah'],
  ['Nah', 'Nahum', ['nah', 'na'], 'nahum'],
  ['Hab', 'Habakkuk', ['hab', 'hb'], 'habakkuk'],
  ['Zeph', 'Zephaniah', ['zeph', 'zep', 'zp'], 'zephaniah'],
  ['Hag', 'Haggai', ['hag', 'hg'], 'haggai'],
  ['Zech', 'Zechariah', ['zech', 'zec', 'zc'], 'zechariah'],
  ['Mal', 'Malachi', ['mal', 'ml'], 'malachi'],
  ['Matt', 'Matthew', ['matt', 'mat', 'mt'], 'matthew'],
  ['Mark', 'Mark', ['mark', 'mrk', 'mar', 'mk', 'mr'], 'mark'],
  ['Luke', 'Luke', ['luke', 'luk', 'lk'], 'luke'],
  ['John', 'John', ['john', 'joh', 'jhn', 'jn'], 'john'],
  ['Acts', 'Acts', ['acts', 'act', 'ac'], 'acts'],
  ['Rom', 'Romans', ['rom', 'ro', 'rm'], 'romans'],
  ['1Cor', '1 Corinthians', ['1cor', '1co', 'icorinthians', 'firstcorinthians'], '1corinthians'],
  ['2Cor', '2 Corinthians', ['2cor', '2co', 'iicorinthians', 'secondcorinthians'], '2corinthians'],
  ['Gal', 'Galatians', ['gal', 'ga'], 'galatians'],
  ['Eph', 'Ephesians', ['eph', 'ephes'], 'ephesians'],
  ['Phil', 'Philippians', ['phil', 'php', 'pp'], 'philippians'],
  ['Col', 'Colossians', ['col', 'co'], 'colossians'],
  ['1Thess', '1 Thessalonians', ['1thess', '1th', '1thes', 'ithessalonians', 'firstthessalonians'], '1thessalonians'],
  ['2Thess', '2 Thessalonians', ['2thess', '2th', '2thes', 'iithessalonians', 'secondthessalonians'], '2thessalonians'],
  ['1Tim', '1 Timothy', ['1tim', '1ti', 'itimothy', 'firsttimothy'], '1timothy'],
  ['2Tim', '2 Timothy', ['2tim', '2ti', 'iitimothy', 'secondtimothy'], '2timothy'],
  ['Titus', 'Titus', ['titus', 'tit', 'ti'], 'titus'],
  ['Phlm', 'Philemon', ['phlm', 'philem', 'phm', 'pm'], 'philemon'],
  ['Heb', 'Hebrews', ['heb'], 'hebrews'],
  ['Jas', 'James', ['jas', 'jm', 'james'], 'james'],
  ['1Pet', '1 Peter', ['1pet', '1pe', '1pt', '1p', 'ipeter', 'firstpeter'], '1peter'],
  ['2Pet', '2 Peter', ['2pet', '2pe', '2pt', '2p', 'iipeter', 'secondpeter'], '2peter'],
  ['1John', '1 John', ['1john', '1jn', '1jo', '1j', 'ijohn', 'firstjohn'], '1john'],
  ['2John', '2 John', ['2john', '2jn', '2jo', '2j', 'iijohn', 'secondjohn'], '2john'],
  ['3John', '3 John', ['3john', '3jn', '3jo', '3j', 'iiijohn', 'thirdjohn'], '3john'],
  ['Jude', 'Jude', ['jude', 'jud', 'jd'], 'jude'],
  ['Rev', 'Revelation', ['rev', 're', 'revelations', 'apocalypse'], 'revelation'],
];
